query getProducts(
  $after: String
  $slug: [String]
  $first: Int = 20
  $orderby: ProductsOrderByEnum = DATE
  $onSale: Boolean
) {
  products(
    first: $first
    after: $after
    where: {
      categoryIn: $slug
      visibility: VISIBLE
      minPrice: 0
      orderby: { field: $orderby, order: DESC }
      status: "publish"
      onSale: $onSale
    }
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
      slug
      type
      databaseId
      id
      averageRating
      reviewCount
      onSale
      ...Terms
      ...ProductCategories
      ...SimpleProduct
      ...VariableProduct
      ...ExternalProduct
    }
  }

  productCategories(where: { slug: $slug }) {
    nodes {
      id
      name
      description
      slug
      uri
      ancestors {
        nodes {
          id
          name
          slug
        }
      }
      parent {
        node {
          id
          name
          slug
        }
      }
    }
  }
}
